nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:4200"]
    allow_methods: ["GET", "POST", "OPTIONS", "PUT", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["http://localhost:4200"]
      allow_headers: ["Content-Type", "Authorization"]
